const vluxBase = "/assets/vlux";

export const vluxAssets = {
  logos: {
    main: `${vluxBase}/logos/vlux-logo-main.png`,
    navbar: `${vluxBase}/logos/vlux-logo-transparent.png`,
    footerMark: `${vluxBase}/logos/vlux-footer-mark.png`,
    watermark: `${vluxBase}/logos/vlux-watermark.png`,
  },
  backgrounds: {
    watermark: `${vluxBase}/backgrounds/vlux-watermark.png`,
  },
  buttons: {
    set: `${vluxBase}/buttons/button-set-neon-glass.png`,
    agendarLlamada: `${vluxBase}/buttons/button-agendar-llamada.png`,
    verDemos: `${vluxBase}/buttons/button-ver-demos.png`,
    escribenos: `${vluxBase}/buttons/button-escribenos.png`,
    solicitarAuditoria: `${vluxBase}/buttons/button-solicitar-auditoria.png`,
    comenzarAhora: `${vluxBase}/buttons/button-comenzar-ahora.png`,
    nuestrosServicios: `${vluxBase}/buttons/button-nuestros-servicios.png`,
    casosDeExito: `${vluxBase}/buttons/button-casos-de-exito.png`,
    conoceMas: `${vluxBase}/buttons/button-conoce-mas.png`,
    agendarDiagnosticoIcon: `${vluxBase}/buttons/icon-agendar-diagnostico.png`,
  },
  icons: {
    aiBrain: `${vluxBase}/icons/ai-brain-neon-glass.png`,
    api: `${vluxBase}/icons/api-neon-glass.png`,
    code: `${vluxBase}/icons/code-neon-glass.png`,
    dashboardBars: `${vluxBase}/icons/dashboard-bars-neon-glass.png`,
    mobileApp: `${vluxBase}/icons/mobile-app-neon-glass.png`,
    network: `${vluxBase}/icons/network-neon-glass.png`,
    processAutomation: `${vluxBase}/icons/process-automation-neon-glass.png`,
    rocket: `${vluxBase}/icons/rocket-neon-glass.png`,
    target: `${vluxBase}/icons/target-neon-glass.png`,
    users: `${vluxBase}/icons/users-neon-glass.png`,
  },
  problem: {
    flow: `${vluxBase}/problem/flujo-rojo.png`,
    report: `${vluxBase}/problem/reporte-rojo.png`,
    visibility: `${vluxBase}/problem/falta-visibilidad-rojo.png`,
    tableAlert: `${vluxBase}/problem/tabla-alerta-rojo.png`,
    whatsapp: `${vluxBase}/problem/whatsapp-rojo.png`,
  },
  process: {
    step01: `${vluxBase}/process/step-01.png`,
    step02: `${vluxBase}/process/step-02.png`,
    step03: `${vluxBase}/process/step-03.png`,
    step04: `${vluxBase}/process/step-04.png`,
    step05: `${vluxBase}/process/step-05.png`,
    step06: `${vluxBase}/process/step-06.png`,
  },
  useCases: {
    manufacturing: `${vluxBase}/use-cases/manufactura.png`,
    administration: `${vluxBase}/use-cases/administracion.png`,
    finance: `${vluxBase}/use-cases/finanzas.png`,
    customerSupport: `${vluxBase}/use-cases/atencion-cliente.png`,
    engineeringCosts: `${vluxBase}/use-cases/ingenieria-costos.png`,
    humanResources: `${vluxBase}/use-cases/recursos-humanos.png`,
  },
  integrations: {
    excel: `${vluxBase}/integrations/excel-neon-glass.png`,
    google: `${vluxBase}/integrations/google-neon-glass.png`,
    solidworks: `${vluxBase}/integrations/solidworks-neon-glass.png`,
    whatsapp: `${vluxBase}/integrations/whatsapp-neon-glass.png`,
    globalShop: `${vluxBase}/integrations/globalshop-neon-glass.png`,
    api: `${vluxBase}/icons/api-neon-glass.png`,
    database: `${vluxBase}/integrations/database-neon-glass.png`,
  },
} as const;
